"""Game tables creation

Revision ID: d6b727c95d09
Revises: 8c868697d19a
Create Date: 2025-08-12 23:11:37.740060-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6b727c95d09'
down_revision: Union[str, Sequence[str], None] = '8c868697d19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_members',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('credit_buyin', sa.Integer(), nullable=False),
    sa.Column('cash_buyin', sa.Integer(), nullable=False),
    sa.Column('final_chips', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rango', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pingo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('received_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'member_id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('pix_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('pix_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)

    op.drop_table('game_members')
    op.drop_table('games')
    # ### end Alembic commands ###
